In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
path = '/gdrive/My Drive/Online ML - MS Aspirants - Sept 2020/Data/'

In [ ]:
Movie_Ratings = pd.read_csv(path+'User_Movie_Ratings.csv')
Movie_Ratings.head()

        Movie Titles  User 1  User 2  ...  User 941  User 942  User 943
0   Toy Story (1995)       5       4  ...         5         0         0
1   GoldenEye (1995)       3       0  ...         0         0         5
2  Four Rooms (1995)       4       0  ...         0         0         0
3  Get Shorty (1995)       3       0  ...         0         0         0
4     Copycat (1995)       3       0  ...         0         0         0

[5 rows x 944 columns]

In [ ]:
Has_Rated = pd.read_csv(path+'Did_User_Rate_Movie.csv')
Has_Rated.head()

         Movie Title  User 1  User 2  ...  User 941  User 942  User 943
0   Toy Story (1995)       1       1  ...         1         0         0
1   GoldenEye (1995)       1       0  ...         0         0         1
2  Four Rooms (1995)       1       0  ...         0         0         0
3  Get Shorty (1995)       1       0  ...         0         0         0
4     Copycat (1995)       1       0  ...         0         0         0

[5 rows x 944 columns]

In [ ]:
num_movies = Movie_Ratings.shape[0]
num_users = Movie_Ratings.shape[1] - 1
print('Total Number of Movies = {}'.format(num_movies))
print('Total Number of Users = {}'.format(num_users))

Total Number of Movies = 1682
Total Number of Users = 943

Assume the number of Genres is 10

> Indented block

In [ ]:
Genres = 10

To find the movie Genre, we need to create movie paramters of the shape -- > Number of movies * Number of Genre

In [ ]:
X =np.random.random(size=(num_movies,Genres))
X.shape

(1682, 10)

In [ ]:
Xparam_num = X.size  #Total Number of X parameters
Xparam_num

16820

To find what kind of movies the user is interested in, we need to create user paramters of the shape -- > Number of users * Number of Genre

In [ ]:
Theta =np.random.random(size=(num_users,Genres))
Theta.shape

(943, 10)

Combining both prameters

In [ ]:
params = np.concatenate((np.ravel(X), np.ravel(Theta)))

In [ ]:
params.shape

(26250,)

X* theta.T must give us the expected ratings that the user will give

Recommendation systems is generally used to recommend movie for which the user will give high ratings so lets take the movie ratings as Y

In [ ]:
Y=Movie_Ratings.drop(columns=['Movie Titles'])
Y.head()

   User 1  User 2  User 3  User 4  ...  User 940  User 941  User 942  User 943
0       5       4       0       0  ...         0         5         0         0
1       3       0       0       0  ...         0         0         0         5
2       4       0       0       0  ...         0         0         0         0
3       3       0       0       0  ...         2         0         0         0
4       3       0       0       0  ...         0         0         0         0

[5 rows x 943 columns]

In [ ]:
Y.shape

(1682, 943)

In [ ]:
R=Has_Rated.drop(columns=['Movie Title'])
R.head()

   User 1  User 2  User 3  User 4  ...  User 940  User 941  User 942  User 943
0       1       1       0       0  ...         0         1         0         0
1       1       0       0       0  ...         0         0         0         1
2       1       0       0       0  ...         0         0         0         0
3       1       0       0       0  ...         1         0         0         0
4       1       0       0       0  ...         0         0         0         0

[5 rows x 943 columns]

Our next step is to add regularization to both the cost and gradient calculations. We'll create one final regularized version of the function (note that this version includes an additional regularisation rate parameter called "lambda").

In [ ]:
def cost(params, Y, R, Genres, reg_rate):
    Y = np.matrix(Y)  # (1682, 943)
    R = np.matrix(R)  # (1682, 943)
    num_movies = Y.shape[0]
    num_users = Y.shape[1]
    
    X_params = params[:Xparam_num]
    theta_params = params[Xparam_num:]

    # reshape the parameter array into parameter matrices
    X = np.matrix(np.reshape(X_params, (num_movies, Genres)))  # (1682, 10)
    Theta = np.matrix(np.reshape(theta_params, (num_users, Genres)))  # (943, 10)
        
    # compute the cost
    error = np.multiply((X * Theta.T) - Y, R)  # (1682, 943)
    squared_error = np.power(error, 2)  # (1682, 943)
    J = (1. / 2) * np.sum(squared_error)
    
    # add the cost regularization
    J = J + ((reg_rate / 2) * np.sum(np.power(Theta, 2)))
    J = J + ((reg_rate / 2) * np.sum(np.power(X, 2)))
    
    
    # initializations
    X_grad = np.zeros(X.shape)  # (1682, 10)
    Theta_grad = np.zeros(Theta.shape)  # (943, 10)
    
    # calculate the gradients with regularization
    X_grad = (error * Theta) + (reg_rate * X)
    Theta_grad = (error.T * X) + (reg_rate * Theta)
    
    # unravel the gradient matrices into a single array
    grad = np.concatenate((np.ravel(X_grad), np.ravel(Theta_grad)))
    
    return J, grad

In [ ]:
J, grad = cost(params, Y, R, Genres, 3.5)    #Testing the Cost function

In [ ]:
reg_rate = 3.5
from scipy.optimize import minimize

fmin = minimize(fun=cost, x0=params, args=(Y, R, Genres, reg_rate), method='CG', jac=True, options={'maxiter': 10000})
fmin

     fun: 43330.76635002544
     jac: array([8.29719155e-06, 7.38684672e-06, 8.41491847e-06, ...,
       1.15293754e-06, 2.46925529e-07, 4.83483137e-07])
 message: 'Desired error not necessarily achieved due to precision loss.'
    nfev: 6425
     nit: 4253
    njev: 6424
  status: 2
 success: False
       x: array([ 0.89699149,  0.66058884,  1.2439229 , ...,  0.78890834,
       -0.17090249,  1.65613743])

In [ ]:
X = np.matrix(np.reshape(fmin.x[:Xparam_num], (num_movies, Genres)))
Theta = np.matrix(np.reshape(fmin.x[Xparam_num:], (num_users, Genres)))

X.shape, Theta.shape

((1682, 10), (943, 10))

In [ ]:
R = (R != 0)
Pred_Recommendations = round(np.multiply((X * Theta.T), R), 0)
Pred_Recommendations.shape

(1682, 943)

In [ ]:
Pred_Recommendations= np.asarray(Pred_Recommendations)

In [ ]:
Pred_Recommendations[:,0]

array([4., 3., 3., ..., 0., 0., 0.])

In [ ]:
Movie_Ratings['User 1']

0       5
1       3
2       4
3       3
4       3
       ..
1677    0
1678    0
1679    0
1680    0
1681    0
Name: User 1, Length: 1682, dtype: int64

In [ ]:
Y.shape[1]

943

In [ ]:
from sklearn.metrics import accuracy_score

avg_acc=[]

for i in range(Y.shape[1]):
  acc = accuracy_score(Movie_Ratings['User '+str(i+1)], Pred_Recommendations[:,i])
  avg_acc.append(acc)
  print('Score of {}th User: {} %'.format(i+1, round(acc*100),2))

Score of 1th User: 92.0 %
Score of 2th User: 98.0 %
Score of 3th User: 98.0 %
Score of 4th User: 99.0 %
Score of 5th User: 94.0 %
Score of 6th User: 94.0 %
Score of 7th User: 86.0 %
Score of 8th User: 98.0 %
Score of 9th User: 99.0 %
Score of 10th User: 97.0 %
Score of 11th User: 95.0 %
Score of 12th User: 99.0 %
Score of 13th User: 83.0 %
Score of 14th User: 97.0 %
Score of 15th User: 97.0 %
Score of 16th User: 96.0 %
Score of 17th User: 99.0 %
Score of 18th User: 92.0 %
Score of 19th User: 99.0 %
Score of 20th User: 99.0 %
Score of 21th User: 95.0 %
Score of 22th User: 96.0 %
Score of 23th User: 96.0 %
Score of 24th User: 98.0 %
Score of 25th User: 99.0 %
Score of 26th User: 97.0 %
Score of 27th User: 99.0 %
Score of 28th User: 98.0 %
Score of 29th User: 99.0 %
Score of 30th User: 99.0 %
Score of 31th User: 99.0 %
Score of 32th User: 99.0 %
Score of 33th User: 100.0 %
Score of 34th User: 99.0 %
Score of 35th User: 99.0 %
Score of 36th User: 99.0 %
Score of 37th User: 98.0 %
Score of 38th User: 96.0 %
Score of 39th User: 99.0 %
Score of 40th User: 99.0 %
Score of 41th User: 99.0 %
Score of 42th User: 95.0 %
Score of 43th User: 94.0 %
Score of 44th User: 95.0 %
Score of 45th User: 99.0 %
Score of 46th User: 99.0 %
Score of 47th User: 99.0 %
Score of 48th User: 98.0 %
Score of 49th User: 93.0 %
Score of 50th User: 99.0 %
Score of 51th User: 99.0 %
Score of 52th User: 99.0 %
Score of 53th User: 99.0 %
Score of 54th User: 98.0 %
Score of 55th User: 99.0 %
Score of 56th User: 95.0 %
Score of 57th User: 97.0 %
Score of 58th User: 95.0 %
Score of 59th User: 88.0 %
Score of 60th User: 95.0 %
Score of 61th User: 99.0 %
Score of 62th User: 93.0 %
Score of 63th User: 98.0 %
Score of 64th User: 94.0 %
Score of 65th User: 98.0 %
Score of 66th User: 98.0 %
Score of 67th User: 99.0 %
Score of 68th User: 99.0 %
Score of 69th User: 98.0 %
Score of 70th User: 97.0 %
Score of 71th User: 99.0 %
Score of 72th User: 96.0 %
Score of 73th User: 98.0 %
Score of 74th User: 99.0 %
Score of 75th User: 97.0 %
Score of 76th User: 98.0 %
Score of 77th User: 97.0 %
Score of 78th User: 99.0 %
Score of 79th User: 98.0 %
Score of 80th User: 99.0 %
Score of 81th User: 98.0 %
Score of 82th User: 95.0 %
Score of 83th User: 95.0 %
Score of 84th User: 98.0 %
Score of 85th User: 93.0 %
Score of 86th User: 99.0 %
Score of 87th User: 95.0 %
Score of 88th User: 99.0 %
Score of 89th User: 97.0 %
Score of 90th User: 91.0 %
Score of 91th User: 97.0 %
Score of 92th User: 90.0 %
Score of 93th User: 99.0 %
Score of 94th User: 90.0 %
Score of 95th User: 91.0 %
Score of 96th User: 98.0 %
Score of 97th User: 98.0 %
Score of 98th User: 99.0 %
Score of 99th User: 96.0 %
Score of 100th User: 99.0 %
Score of 101th User: 98.0 %
Score of 102th User: 95.0 %
Score of 103th User: 99.0 %
Score of 104th User: 96.0 %
Score of 105th User: 99.0 %
Score of 106th User: 98.0 %
Score of 107th User: 99.0 %
Score of 108th User: 99.0 %
Score of 109th User: 92.0 %
Score of 110th User: 97.0 %
Score of 111th User: 99.0 %
Score of 112th User: 99.0 %
Score of 113th User: 98.0 %
Score of 114th User: 98.0 %
Score of 115th User: 97.0 %
Score of 116th User: 95.0 %
Score of 117th User: 98.0 %
Score of 118th User: 99.0 %
Score of 119th User: 94.0 %
Score of 120th User: 99.0 %
Score of 121th User: 97.0 %
Score of 122th User: 98.0 %
Score of 123th User: 98.0 %
Score of 124th User: 99.0 %
Score of 125th User: 95.0 %
Score of 126th User: 98.0 %
Score of 127th User: 99.0 %
Score of 128th User: 94.0 %
Score of 129th User: 99.0 %
Score of 130th User: 90.0 %
Score of 131th User: 99.0 %
Score of 132th User: 100.0 %
Score of 133th User: 99.0 %
Score of 134th User: 99.0 %
Score of 135th User: 99.0 %
Score of 136th User: 99.0 %
Score of 137th User: 99.0 %
Score of 138th User: 99.0 %
Score of 139th User: 99.0 %
Score of 140th User: 100.0 %
Score of 141th User: 97.0 %
Score of 142th User: 99.0 %
Score of 143th User: 99.0 %
Score of 144th User: 95.0 %
Score of 145th User: 90.0 %
Score of 146th User: 99.0 %
Score of 147th User: 99.0 %
Score of 148th User: 97.0 %
Score of 149th User: 99.0 %
Score of 150th User: 99.0 %
Score of 151th User: 92.0 %
Score of 152th User: 97.0 %
Score of 153th User: 99.0 %
Score of 154th User: 99.0 %
Score of 155th User: 100.0 %
Score of 156th User: 99.0 %
Score of 157th User: 99.0 %
Score of 158th User: 95.0 %
Score of 159th User: 96.0 %
Score of 160th User: 97.0 %
Score of 161th User: 98.0 %
Score of 162th User: 99.0 %
Score of 163th User: 100.0 %
Score of 164th User: 99.0 %
Score of 165th User: 99.0 %
Score of 166th User: 99.0 %
Score of 167th User: 98.0 %
Score of 168th User: 97.0 %
Score of 169th User: 99.0 %
Score of 170th User: 99.0 %
Score of 171th User: 99.0 %
Score of 172th User: 99.0 %
Score of 173th User: 99.0 %
Score of 174th User: 95.0 %
Score of 175th User: 99.0 %
Score of 176th User: 98.0 %
Score of 177th User: 97.0 %
Score of 178th User: 93.0 %
Score of 179th User: 98.0 %
Score of 180th User: 98.0 %
Score of 181th User: 90.0 %
Score of 182th User: 99.0 %
Score of 183th User: 98.0 %
Score of 184th User: 94.0 %
Score of 185th User: 99.0 %
Score of 186th User: 97.0 %
Score of 187th User: 99.0 %
Score of 188th User: 96.0 %
Score of 189th User: 94.0 %
Score of 190th User: 98.0 %
Score of 191th User: 99.0 %
Score of 192th User: 99.0 %
Score of 193th User: 97.0 %
Score of 194th User: 91.0 %
Score of 195th User: 97.0 %
Score of 196th User: 99.0 %
Score of 197th User: 96.0 %
Score of 198th User: 96.0 %
Score of 199th User: 99.0 %
Score of 200th User: 95.0 %
Score of 201th User: 88.0 %
Score of 202th User: 99.0 %
Score of 203th User: 98.0 %
Score of 204th User: 99.0 %
Score of 205th User: 99.0 %
Score of 206th User: 98.0 %
Score of 207th User: 95.0 %
Score of 208th User: 99.0 %
Score of 209th User: 99.0 %
Score of 210th User: 97.0 %
Score of 211th User: 99.0 %
Score of 212th User: 99.0 %
Score of 213th User: 97.0 %
Score of 214th User: 96.0 %
Score of 215th User: 97.0 %
Score of 216th User: 96.0 %
Score of 217th User: 97.0 %
Score of 218th User: 99.0 %
Score of 219th User: 99.0 %
Score of 220th User: 99.0 %
Score of 221th User: 96.0 %
Score of 222th User: 88.0 %
Score of 223th User: 96.0 %
Score of 224th User: 96.0 %
Score of 225th User: 99.0 %
Score of 226th User: 99.0 %
Score of 227th User: 98.0 %
Score of 228th User: 99.0 %
Score of 229th User: 99.0 %
Score of 230th User: 96.0 %
Score of 231th User: 99.0 %
Score of 232th User: 98.0 %
Score of 233th User: 97.0 %
Score of 234th User: 87.0 %
Score of 235th User: 98.0 %
Score of 236th User: 95.0 %
Score of 237th User: 99.0 %
Score of 238th User: 99.0 %
Score of 239th User: 95.0 %
Score of 240th User: 99.0 %
Score of 241th User: 99.0 %
Score of 242th User: 99.0 %
Score of 243th User: 98.0 %
Score of 244th User: 94.0 %
Score of 245th User: 99.0 %
Score of 246th User: 94.0 %
Score of 247th User: 99.0 %
Score of 248th User: 98.0 %
Score of 249th User: 96.0 %
Score of 250th User: 96.0 %
Score of 251th User: 98.0 %
Score of 252th User: 100.0 %
Score of 253th User: 97.0 %
Score of 254th User: 96.0 %
Score of 255th User: 97.0 %
Score of 256th User: 93.0 %
Score of 257th User: 99.0 %
Score of 258th User: 99.0 %
Score of 259th User: 99.0 %
Score of 260th User: 99.0 %
Score of 261th User: 99.0 %
Score of 262th User: 96.0 %
Score of 263th User: 96.0 %
Score of 264th User: 97.0 %
Score of 265th User: 99.0 %
Score of 266th User: 99.0 %
Score of 267th User: 97.0 %
Score of 268th User: 90.0 %
Score of 269th User: 90.0 %
Score of 270th User: 96.0 %
Score of 271th User: 92.0 %
Score of 272th User: 99.0 %
Score of 273th User: 100.0 %
Score of 274th User: 98.0 %
Score of 275th User: 98.0 %
Score of 276th User: 90.0 %
Score of 277th User: 99.0 %
Score of 278th User: 99.0 %
Score of 279th User: 89.0 %
Score of 280th User: 92.0 %
Score of 281th User: 99.0 %
Score of 282th User: 100.0 %
Score of 283th User: 99.0 %
Score of 284th User: 99.0 %
Score of 285th User: 99.0 %
Score of 286th User: 92.0 %
Score of 287th User: 98.0 %
Score of 288th User: 98.0 %
Score of 289th User: 99.0 %
Score of 290th User: 95.0 %
Score of 291th User: 93.0 %
Score of 292th User: 97.0 %
Score of 293th User: 89.0 %
Score of 294th User: 96.0 %
Score of 295th User: 95.0 %
Score of 296th User: 96.0 %
Score of 297th User: 94.0 %
Score of 298th User: 96.0 %
Score of 299th User: 92.0 %
Score of 300th User: 99.0 %
Score of 301th User: 91.0 %
Score of 302th User: 100.0 %
Score of 303th User: 89.0 %
Score of 304th User: 99.0 %
Score of 305th User: 92.0 %
Score of 306th User: 99.0 %
Score of 307th User: 96.0 %
Score of 308th User: 90.0 %
Score of 309th User: 99.0 %
Score of 310th User: 99.0 %
Score of 311th User: 92.0 %
Score of 312th User: 94.0 %
Score of 313th User: 92.0 %
Score of 314th User: 93.0 %
Score of 315th User: 98.0 %
Score of 316th User: 97.0 %
Score of 317th User: 99.0 %
Score of 318th User: 94.0 %
Score of 319th User: 99.0 %
Score of 320th User: 96.0 %
Score of 321th User: 97.0 %
Score of 322th User: 99.0 %
Score of 323th User: 98.0 %
Score of 324th User: 98.0 %
Score of 325th User: 96.0 %
Score of 326th User: 93.0 %
Score of 327th User: 92.0 %
Score of 328th User: 92.0 %
Score of 329th User: 99.0 %
Score of 330th User: 97.0 %
Score of 331th User: 98.0 %
Score of 332th User: 95.0 %
Score of 333th User: 99.0 %
Score of 334th User: 92.0 %
Score of 335th User: 99.0 %
Score of 336th User: 95.0 %
Score of 337th User: 99.0 %
Score of 338th User: 98.0 %
Score of 339th User: 94.0 %
Score of 340th User: 99.0 %
Score of 341th User: 99.0 %
Score of 342th User: 94.0 %
Score of 343th User: 93.0 %
Score of 344th User: 95.0 %
Score of 345th User: 94.0 %
Score of 346th User: 94.0 %
Score of 347th User: 93.0 %
Score of 348th User: 99.0 %
Score of 349th User: 99.0 %
Score of 350th User: 99.0 %
Score of 351th User: 99.0 %
Score of 352th User: 99.0 %
Score of 353th User: 99.0 %
Score of 354th User: 94.0 %
Score of 355th User: 99.0 %
Score of 356th User: 99.0 %
Score of 357th User: 98.0 %
Score of 358th User: 98.0 %
Score of 359th User: 99.0 %
Score of 360th User: 98.0 %
Score of 361th User: 96.0 %
Score of 362th User: 99.0 %
Score of 363th User: 89.0 %
Score of 364th User: 99.0 %
Score of 365th User: 98.0 %
Score of 366th User: 99.0 %
Score of 367th User: 99.0 %
Score of 368th User: 99.0 %
Score of 369th User: 100.0 %
Score of 370th User: 98.0 %
Score of 371th User: 98.0 %
Score of 372th User: 98.0 %
Score of 373th User: 94.0 %
Score of 374th User: 91.0 %
Score of 375th User: 99.0 %
Score of 376th User: 100.0 %
Score of 377th User: 99.0 %
Score of 378th User: 91.0 %
Score of 379th User: 95.0 %
Score of 380th User: 95.0 %
Score of 381th User: 96.0 %
Score of 382th User: 98.0 %
Score of 383th User: 98.0 %
Score of 384th User: 100.0 %
Score of 385th User: 91.0 %
Score of 386th User: 99.0 %
Score of 387th User: 91.0 %
Score of 388th User: 99.0 %
Score of 389th User: 93.0 %
Score of 390th User: 99.0 %
Score of 391th User: 96.0 %
Score of 392th User: 97.0 %
Score of 393th User: 87.0 %
Score of 394th User: 96.0 %
Score of 395th User: 98.0 %
Score of 396th User: 99.0 %
Score of 397th User: 97.0 %
Score of 398th User: 95.0 %
Score of 399th User: 91.0 %
Score of 400th User: 100.0 %
Score of 401th User: 95.0 %
Score of 402th User: 99.0 %
Score of 403th User: 98.0 %
Score of 404th User: 99.0 %
Score of 405th User: 91.0 %
Score of 406th User: 88.0 %
Score of 407th User: 94.0 %
Score of 408th User: 99.0 %
Score of 409th User: 94.0 %
Score of 410th User: 99.0 %
Score of 411th User: 98.0 %
Score of 412th User: 99.0 %
Score of 413th User: 99.0 %
Score of 414th User: 99.0 %
Score of 415th User: 99.0 %
Score of 416th User: 86.0 %
Score of 417th User: 89.0 %
Score of 418th User: 99.0 %
Score of 419th User: 99.0 %
Score of 420th User: 99.0 %
Score of 421th User: 98.0 %
Score of 422th User: 97.0 %
Score of 423th User: 98.0 %
Score of 424th User: 99.0 %
Score of 425th User: 93.0 %
Score of 426th User: 97.0 %
Score of 427th User: 99.0 %
Score of 428th User: 99.0 %
Score of 429th User: 89.0 %
Score of 430th User: 98.0 %
Score of 431th User: 100.0 %
Score of 432th User: 98.0 %
Score of 433th User: 99.0 %
Score of 434th User: 98.0 %
Score of 435th User: 88.0 %
Score of 436th User: 96.0 %
Score of 437th User: 92.0 %
Score of 438th User: 99.0 %
Score of 439th User: 99.0 %
Score of 440th User: 98.0 %
Score of 441th User: 99.0 %
Score of 442th User: 96.0 %
Score of 443th User: 99.0 %
Score of 444th User: 99.0 %
Score of 445th User: 96.0 %
Score of 446th User: 99.0 %
Score of 447th User: 96.0 %
Score of 448th User: 99.0 %
Score of 449th User: 98.0 %
Score of 450th User: 85.0 %
Score of 451th User: 97.0 %
Score of 452th User: 94.0 %
Score of 453th User: 96.0 %
Score of 454th User: 93.0 %
Score of 455th User: 95.0 %
Score of 456th User: 94.0 %
Score of 457th User: 95.0 %
Score of 458th User: 94.0 %
Score of 459th User: 96.0 %
Score of 460th User: 98.0 %
Score of 461th User: 99.0 %
Score of 462th User: 99.0 %
Score of 463th User: 96.0 %
Score of 464th User: 99.0 %
Score of 465th User: 98.0 %
Score of 466th User: 96.0 %
Score of 467th User: 98.0 %
Score of 468th User: 96.0 %
Score of 469th User: 100.0 %
Score of 470th User: 98.0 %
Score of 471th User: 99.0 %
Score of 472th User: 93.0 %
Score of 473th User: 99.0 %
Score of 474th User: 92.0 %
Score of 475th User: 99.0 %
Score of 476th User: 97.0 %
Score of 477th User: 99.0 %
Score of 478th User: 97.0 %
Score of 479th User: 94.0 %
Score of 480th User: 98.0 %
Score of 481th User: 98.0 %
Score of 482th User: 99.0 %
Score of 483th User: 99.0 %
Score of 484th User: 97.0 %
Score of 485th User: 99.0 %
Score of 486th User: 95.0 %
Score of 487th User: 93.0 %
Score of 488th User: 95.0 %
Score of 489th User: 96.0 %
Score of 490th User: 98.0 %
Score of 491th User: 99.0 %
Score of 492th User: 98.0 %
Score of 493th User: 95.0 %
Score of 494th User: 99.0 %
Score of 495th User: 93.0 %
Score of 496th User: 96.0 %
Score of 497th User: 93.0 %
Score of 498th User: 96.0 %
Score of 499th User: 97.0 %
Score of 500th User: 94.0 %
Score of 501th User: 99.0 %
Score of 502th User: 99.0 %
Score of 503th User: 95.0 %
Score of 504th User: 94.0 %
Score of 505th User: 97.0 %
Score of 506th User: 94.0 %
Score of 507th User: 99.0 %
Score of 508th User: 97.0 %
Score of 509th User: 99.0 %
Score of 510th User: 100.0 %
Score of 511th User: 99.0 %
Score of 512th User: 99.0 %
Score of 513th User: 99.0 %
Score of 514th User: 94.0 %
Score of 515th User: 99.0 %
Score of 516th User: 100.0 %
Score of 517th User: 99.0 %
Score of 518th User: 97.0 %
Score of 519th User: 99.0 %
Score of 520th User: 99.0 %
Score of 521th User: 96.0 %
Score of 522th User: 99.0 %
Score of 523th User: 98.0 %
Score of 524th User: 90.0 %
Score of 525th User: 99.0 %
Score of 526th User: 98.0 %
Score of 527th User: 96.0 %
Score of 528th User: 99.0 %
Score of 529th User: 99.0 %
Score of 530th User: 99.0 %
Score of 531th User: 99.0 %
Score of 532th User: 93.0 %
Score of 533th User: 93.0 %
Score of 534th User: 98.0 %
Score of 535th User: 94.0 %
Score of 536th User: 95.0 %
Score of 537th User: 88.0 %
Score of 538th User: 98.0 %
Score of 539th User: 98.0 %
Score of 540th User: 99.0 %
Score of 541th User: 96.0 %
Score of 542th User: 96.0 %
Score of 543th User: 95.0 %
Score of 544th User: 99.0 %
Score of 545th User: 96.0 %
Score of 546th User: 98.0 %
Score of 547th User: 99.0 %
Score of 548th User: 95.0 %
Score of 549th User: 100.0 %
Score of 550th User: 98.0 %
Score of 551th User: 88.0 %
Score of 552th User: 98.0 %
Score of 553th User: 98.0 %
Score of 554th User: 97.0 %
Score of 555th User: 99.0 %
Score of 556th User: 99.0 %
Score of 557th User: 98.0 %
Score of 558th User: 100.0 %
Score of 559th User: 98.0 %
Score of 560th User: 97.0 %
Score of 561th User: 91.0 %
Score of 562th User: 97.0 %
Score of 563th User: 99.0 %
Score of 564th User: 99.0 %
Score of 565th User: 99.0 %
Score of 566th User: 95.0 %
Score of 567th User: 96.0 %
Score of 568th User: 97.0 %
Score of 569th User: 98.0 %
Score of 570th User: 99.0 %
Score of 571th User: 100.0 %
Score of 572th User: 99.0 %
Score of 573th User: 99.0 %
Score of 574th User: 98.0 %
Score of 575th User: 99.0 %
Score of 576th User: 100.0 %
Score of 577th User: 95.0 %
Score of 578th User: 99.0 %
Score of 579th User: 98.0 %
Score of 580th User: 99.0 %
Score of 581th User: 99.0 %
Score of 582th User: 98.0 %
Score of 583th User: 99.0 %
Score of 584th User: 99.0 %
Score of 585th User: 98.0 %
Score of 586th User: 95.0 %
Score of 587th User: 97.0 %
Score of 588th User: 92.0 %
Score of 589th User: 99.0 %
Score of 590th User: 99.0 %
Score of 591th User: 98.0 %
Score of 592th User: 90.0 %
Score of 593th User: 95.0 %
Score of 594th User: 100.0 %
Score of 595th User: 98.0 %
Score of 596th User: 99.0 %
Score of 597th User: 99.0 %
Score of 598th User: 99.0 %
Score of 599th User: 98.0 %
Score of 600th User: 98.0 %
Score of 601th User: 95.0 %
Score of 602th User: 99.0 %
Score of 603th User: 99.0 %
Score of 604th User: 99.0 %
Score of 605th User: 97.0 %
Score of 606th User: 93.0 %
Score of 607th User: 99.0 %
Score of 608th User: 95.0 %
Score of 609th User: 99.0 %
Score of 610th User: 98.0 %
Score of 611th User: 99.0 %
Score of 612th User: 99.0 %
Score of 613th User: 99.0 %
Score of 614th User: 99.0 %
Score of 615th User: 98.0 %
Score of 616th User: 99.0 %
Score of 617th User: 97.0 %
Score of 618th User: 94.0 %
Score of 619th User: 97.0 %
Score of 620th User: 96.0 %
Score of 621th User: 95.0 %
Score of 622th User: 93.0 %
Score of 623th User: 99.0 %
Score of 624th User: 97.0 %
Score of 625th User: 97.0 %
Score of 626th User: 99.0 %
Score of 627th User: 94.0 %
Score of 628th User: 99.0 %
Score of 629th User: 96.0 %
Score of 630th User: 97.0 %
Score of 631th User: 100.0 %
Score of 632th User: 96.0 %
Score of 633th User: 98.0 %
Score of 634th User: 96.0 %
Score of 635th User: 99.0 %
Score of 636th User: 99.0 %
Score of 637th User: 97.0 %
Score of 638th User: 98.0 %
Score of 639th User: 95.0 %
Score of 640th User: 98.0 %
Score of 641th User: 99.0 %
Score of 642th User: 92.0 %
Score of 643th User: 95.0 %
Score of 644th User: 99.0 %
Score of 645th User: 98.0 %
Score of 646th User: 99.0 %
Score of 647th User: 98.0 %
Score of 648th User: 91.0 %
Score of 649th User: 99.0 %
Score of 650th User: 93.0 %
Score of 651th User: 99.0 %
Score of 652th User: 99.0 %
Score of 653th User: 91.0 %
Score of 654th User: 96.0 %
Score of 655th User: 84.0 %
Score of 656th User: 99.0 %
Score of 657th User: 99.0 %
Score of 658th User: 98.0 %
Score of 659th User: 95.0 %
Score of 660th User: 94.0 %
Score of 661th User: 97.0 %
Score of 662th User: 99.0 %
Score of 663th User: 95.0 %
Score of 664th User: 96.0 %
Score of 665th User: 96.0 %
Score of 666th User: 94.0 %
Score of 667th User: 98.0 %
Score of 668th User: 99.0 %
Score of 669th User: 96.0 %
Score of 670th User: 98.0 %
Score of 671th User: 96.0 %
Score of 672th User: 99.0 %
Score of 673th User: 99.0 %
Score of 674th User: 99.0 %
Score of 675th User: 99.0 %
Score of 676th User: 98.0 %
Score of 677th User: 98.0 %
Score of 678th User: 99.0 %
Score of 679th User: 98.0 %
Score of 680th User: 99.0 %
Score of 681th User: 99.0 %
Score of 682th User: 87.0 %
Score of 683th User: 98.0 %
Score of 684th User: 98.0 %
Score of 685th User: 99.0 %
Score of 686th User: 99.0 %
Score of 687th User: 99.0 %
Score of 688th User: 99.0 %
Score of 689th User: 99.0 %
Score of 690th User: 96.0 %
Score of 691th User: 99.0 %
Score of 692th User: 98.0 %
Score of 693th User: 95.0 %
Score of 694th User: 96.0 %
Score of 695th User: 99.0 %
Score of 696th User: 99.0 %
Score of 697th User: 97.0 %
Score of 698th User: 95.0 %
Score of 699th User: 96.0 %
Score of 700th User: 100.0 %
Score of 701th User: 99.0 %
Score of 702th User: 99.0 %
Score of 703th User: 99.0 %
Score of 704th User: 97.0 %
Score of 705th User: 96.0 %
Score of 706th User: 99.0 %
Score of 707th User: 93.0 %
Score of 708th User: 97.0 %
Score of 709th User: 96.0 %
Score of 710th User: 98.0 %
Score of 711th User: 95.0 %
Score of 712th User: 96.0 %
Score of 713th User: 99.0 %
Score of 714th User: 99.0 %
Score of 715th User: 96.0 %
Score of 716th User: 92.0 %
Score of 717th User: 98.0 %

In [ ]:
Average_accuracy = sum(avg_acc)/Y.shape[1]
print('Average Accuracy in predictions for all users : {} %'.format(round(Average_accuracy*100),2))

Average Accuracy in predictions for all users : 97.0 %

### **Predictions for a new User**

> Indented block

In [ ]:
Movie_Ratings['Movie Titles'][0]

'Toy Story (1995)'

# **Add some new ratings for the new user**

In [ ]:
new_ratings = np.zeros((1682, 1))

new_ratings[0] = 4
new_ratings[6] = 3
new_ratings[11] = 5
new_ratings[53] = 4
new_ratings[63] = 5
new_ratings[65] = 3
new_ratings[68] = 5
new_ratings[97] = 2
new_ratings[182] = 4
new_ratings[225] = 5
new_ratings[354] = 5

print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][0], str(int(new_ratings[0]))))
print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][6], str(int(new_ratings[6]))))
print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][11], str(int(new_ratings[11]))))
print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][53], str(int(new_ratings[53]))))
print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][63], str(int(new_ratings[63]))))
print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][65], str(int(new_ratings[65]))))
print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][68], str(int(new_ratings[68]))))
print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][97], str(int(new_ratings[97]))))
print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][182], str(int(new_ratings[182]))))
print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][225], str(int(new_ratings[225]))))
print('Rated {} with {} stars.'.format(Movie_Ratings['Movie Titles'][354], str(int(new_ratings[354]))))

Rated Toy Story (1995) with 4 stars.
Rated Twelve Monkeys (1995) with 3 stars.
Rated Usual Suspects, The (1995) with 5 stars.
Rated Outbreak (1995) with 4 stars.
Rated Shawshank Redemption, The (1994) with 5 stars.
Rated While You Were Sleeping (1995) with 3 stars.
Rated Forrest Gump (1994) with 5 stars.
Rated Silence of the Lambs, The (1991) with 2 stars.
Rated Alien (1979) with 4 stars.
Rated Die Hard 2 (1990) with 5 stars.
Rated Sphere (1998) with 5 stars.

## **We can add this custom ratings vector to the data set so it gets included in the model.**## **We can add this custom ratings vector to the data set so it gets included in the model.**

In [ ]:
Y = np.append(Y, new_ratings, axis=1)
R = np.append(R, new_ratings != 0,  axis=1)

We're now ready to train the collaborative filtering model. We're going to run the optimization routine using our cost function, parameter vector, and data matrices at inputs.

In [ ]:
Y.shape, R.shape

((1682, 944), (1682, 944))

In [ ]:
num_movies = Y.shape[0]
num_users = Y.shape[1]


X = np.random.random(size=(num_movies, Genres))
Theta = np.random.random(size=(num_users, Genres))

params = np.concatenate((np.ravel(X), np.ravel(Theta)))

X.shape, Theta.shape

((1682, 10), (944, 10))

In [ ]:
reg_rate = 3.5
from scipy.optimize import minimize

fmin = minimize(fun=cost, x0=params, args=(Y, R, Genres, reg_rate), method='CG', jac=True, options={'maxiter': 10000})
fmin

     fun: 43343.198811568676
     jac: array([-3.95953006e-07, -2.57076642e-06, -9.95038367e-07, ...,
       -7.77869302e-08,  3.43853226e-08,  6.72743252e-07])
 message: 'Desired error not necessarily achieved due to precision loss.'
    nfev: 4919
     nit: 3294
    njev: 4918
  status: 2
 success: False
       x: array([0.32251927, 0.50303655, 0.43642173, ..., 0.78837285, 0.49610425,
       1.09921335])

In [ ]:
fmin.x.shape

In [ ]:
Xparam_num

16820

In [ ]:
X = np.matrix(np.reshape(fmin.x[:Xparam_num], (num_movies, Genres)))
X.shape

(1682, 10)

In [ ]:
Theta = np.matrix(np.reshape(fmin.x[Xparam_num:], (num_users, Genres)))

Theta.shape

(944, 10)

In [ ]:
R = (R != 0)
Pred_Recommendations = np.multiply((X * Theta.T), R)
Pred_Recommendations.shape

(1682, 944)

Our trained parameters are now in X and Theta. We can use these to create some recommendations for the user we added earlier.

In [ ]:
R = (R != 1)
New_Recommendations = np.multiply((X * Theta.T), R)
my_recs = New_Recommendations[:, 943]

In [ ]:
my_recs.shape

(1682, 1)

In [ ]:
idx = np.argsort(my_recs, axis=0, )[::-1]
print(idx)

[[  63]
 [  68]
 [  11]
 ...
 [1126]
 [1127]
 [ 840]]

In [ ]:
idx.shape

(1682, 1)

In [ ]:
print("Top 10 movie predictions:")
for i in range(20):
    j = int(idx[i])
    print('Predicted rating of {0} for movie {1}.'.format(str((round(float(my_recs[j]),1))),Movie_Ratings['Movie Titles'][j]))

Top 10 movie predictions:
Predicted rating of 4.3 for movie Shawshank Redemption, The (1994).
Predicted rating of 4.2 for movie Forrest Gump (1994).
Predicted rating of 4.0 for movie Usual Suspects, The (1995).
Predicted rating of 3.9 for movie Alien (1979).
Predicted rating of 3.9 for movie Die Hard 2 (1990).
Predicted rating of 3.8 for movie Toy Story (1995).
Predicted rating of 3.7 for movie Silence of the Lambs, The (1991).
Predicted rating of 3.5 for movie Outbreak (1995).
Predicted rating of 3.4 for movie Sphere (1998).
Predicted rating of 3.4 for movie Twelve Monkeys (1995).
Predicted rating of 3.3 for movie While You Were Sleeping (1995).
Predicted rating of 0.0 for movie Quick and the Dead, The (1995).
Predicted rating of 0.0 for movie Clear and Present Danger (1994).
Predicted rating of 0.0 for movie Stephen King's The Langoliers (1995).
Predicted rating of 0.0 for movie Mary Shelley's Frankenstein (1994).
Predicted rating of 0.0 for movie Tales from the Hood (1995).
Predicted rating of 0.0 for movie Kid in King Arthur's Court, A (1995).
Predicted rating of 0.0 for movie Interview with the Vampire (1994).
Predicted rating of 0.0 for movie Village of the Damned (1995).
Predicted rating of 0.0 for movie Wyatt Earp (1994).